name: markdown-lint
on:
  pull_request: {}
permissions:
  statuses: write
  checks: write
  contents: read
  pull-requests: read
jobs:
  markdown-lint:
    uses: actionsforge/actions/.github/workflows/markdown-lint.yml@main